server:
  port: 8762

# eureka
eureka:
  instance:
    hostname: lawliet-eureka2
  client:
    service-url:
      defaultZone: http://lawliet-eureka1:8761/eureka/

# spring
spring:
  profiles:
    active: peer2