server:
  port: 8761

# eureka
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

# spring
spring:
  application:
    name: lawliet-eureka